### ISSUE TITLE
Object-oriented day 16

### ISSUE THREAD

**Issue by Lammatian** [mtsochacki/advent-of-code-2021#18]
Day 16 is a case of a problem which nicely fits into the object-oriented paradigm of programming. We have `Packet`s that can either be `LiteralPackets` or `OperatorPackets` (opportunity to learn about classes, inheritance and polymorphism). I would rewrite the code to take advantage of that. Take a look at the branch `day16-matix` for reference

**Comment by mtsochacki** [comment]
#39 will hopefully cover this
